spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/itemservice
    username: sa
    password:
    driver-class-name: org.postgresql.Driver
#jdbcTemplate sql log
logging:
  level:
    org:
      springframework:
        jdbc: debug